name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - run: cargo xtask build
      - run: readelf -W --version-info target/runtime/LinUwUx.so
      - run: gh release create "$GITHUB_REF_NAME" target/runtime/LinUwUx.so --title "$GITHUB_REF_NAME" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
